### ISSUE TITLE
Plugin keeps crashing repeatedly as soon as I type something in a Vala source file

### ISSUE THREAD

**Issue by pmjobin** [vala-lang/vala-vscode#21]
Here is the VS Code setup I currently use:

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:44:09.336Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.16-301.fc37.x86_64
Sandboxed: No

Vala plugin v1.0.8
Vala language server 0.48.5-7.6 (from OBS repo)
Meson plugin v1.7.1 (mesonbuild)
Meson 0.63.2 (from Fedora repo)

[log.txt](https://github.com/vala-lang/vala-vscode/files/9912583/log.txt)

**Comment by Prince781** [comment]
@pmjobin thanks, glad to know the issue is fixed now. Sorry I didn't get to reproduce your issue. If you're feeling extra generous (or curious), you could bisect so at least we know which commit fixed it.
