### ISSUE TITLE
is vala a gud lang

### ISSUE THREAD

**Issue by tizu69** [vala-lang/vala-vscode#23]
pls tell I want to write os and this is totally rerl aiphihahihiauhwruhorffrdcuhjn (I'm sorry ^^)

**Comment by bumbelbee777** [comment]
YOU MORON WRITE AN OS IN C OR C++, AND IF YOU HAVE BALLS WRITE IT IN 16 BIT X86 ASSEMBLER

**Comment by tizu69** [comment]
but Vala compiles code down to blazingly fast, fully native binaries. You're also able to reuse existing C Code in your Vala programs as well as generate C Code from Vala.

**Comment by bumbelbee777** [comment]
go ahead implement an interrupt handler in vala

**Comment by tizu69** [comment]
> go ahead implement an interrupt handler in vala

~~I'll interrupt joe mama~~

**Comment by tizu69** [comment]
okay let's stop idk if The Vala community on GitHub likes this :) lmao
