### ISSUE TITLE
getting GTK elementary OS Granite intellisense, build and debug working under linux

### ISSUE THREAD

**Issue by foodmonkey** [vala-lang/vala-vscode#24]
hi,
eOS 7 (Horus)
latest VS Code
vala language server installed
your vala language extension installed in vs code
meson build system
valac version Vala 0.56.4
LLDB extension

have got vala intellisense and linting working but when using Granite and GTK libs get a "namespace not found"
error in the following code

using Granite;
using Granite.Widgets;
using Gtk;

after some research found the following tutorial which details adding GTK support for a cpp project

https://www.appsloveworld.com/cplus/100/81/how-to-configure-vscode-for-gtk3-for-intellisense-build-debug-and-g

so output from the following command shows the include libs and the compiler directives to put into the following files (with the obvious alterations made according to the above tutorial)

 .vscode/c_cpp_properties.json (intellisense), 
.vscode/tasks.json (build),
.vscode/launch.json (debug)

foodmonkey@fmiMac-dev:/usr/share/doc/elementary-sdk$ pkg-config --cflags --libs gtk+-3.0

-pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0

so there are some questions

1. w̶h̶e̶r̶e̶ d̶o̶ t̶h̶e̶s̶e̶ f̶i̶l̶e̶s̶ l̶i̶v̶e̶ a̶n̶d̶ what should they be called to bring this into the vala intellisense/build/debug and what changes should be made for  the vala specific json files?

2.  d̶o̶e̶s̶ t̶h̶i̶s̶ d̶i̶r̶e̶c̶t̶o̶r̶y̶ l̶i̶v̶e̶ i̶n̶ t̶h̶e̶ a̶c̶t̶u̶a̶l̶ r̶o̶o̶t̶ d̶i̶r̶e̶c̶t̶o̶r̶y̶ f̶o̶r̶ t̶h̶e̶ p̶r̶o̶j̶e̶c̶t̶ o̶r̶ d̶o̶e̶s̶ i̶t̶ l̶i̶v̶e̶ a̶t̶ a̶ g̶l̶o̶b̶a̶l̶ l̶e̶v̶e̶l̶ f̶o̶r̶ V̶S̶ C̶o̶d̶e̶ v̶a̶l̶a̶ p̶r̶o̶j̶e̶c̶t̶s̶?̶   

   _the files live in the .vscode directory under the project root directory_

for the Granite stuff i get

foodmonkey@fmiMac-dev:/usr/share/doc/elementary-sdk$ dpkg-query -l 'libgranite*'

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version                      Architecture Description
+++-===================-============================-============-===============================================
ii  libgranite-7-common 7.2.0+r2390+pkg132~ubuntu7.1 all          extension of GTK+ libraries (common files)
ii  libgranite-7-dev          7.2.0+r2390+pkg132~ubuntu7.1 amd64        extension of GTK+ libraries (development files)
ii  libgranite-common    6.2.0+r2223+pkg122~ubuntu7.1 all          extension of GTK+ libraries (common files)
ii  libgranite-dev             6.2.0+r2223+pkg122~ubuntu7.1 amd64        extension of GTK+ libraries (development files)
un  libgranite0               <none>                       <none>       (no description available)
ii  libgranite6:amd64     6.2.0+r2223+pkg122~ubuntu7.1 amd64        extension of GTK+ libraries
ii  libgranite7:amd64     7.2.0+r2390+pkg132~ubuntu7.1 amd64        extension of GTK+ libraries

so i can run pkg-config --cflags --libs "granite package name" to generate to include list

3. but which of the granite packages in the above list should be the one used to generate the include list for another section in the json file? (to get the intellisense/build/debug working for the Granite 7 stuff?

i also notice that there are the following header files in the include path

foodmonkey@fmiMac-dev:/usr/include$ ls /usr/include/granite*
/usr/include/granite:
granite.h

/usr/include/granite-7:
granite-7.h

any comments would be extremely helpful and if this gets solved it could be included as part of the turtorial for setting up Vala under VS Code for linux

cheers,
G

**Comment by foodmonkey** [comment]
and then maybe could fork valdo and add a template for vala GTK/Granite projects

**Comment by foodmonkey** [comment]
ok further research answered one of the questions - the files live in the .vscode directory under the root project directory

**Comment by benwaffle** [comment]
Vala Language Server gets dependencies from `compile_commands.json` (which is generated by running `meson`), or from `meson.build`. Make sure you can compile your project with meson successfully.

changing these files will not fix your problem:
```
.vscode/c_cpp_properties.json (intellisense),
.vscode/tasks.json (build),
.vscode/launch.json (debug)
```

**Comment by foodmonkey** [comment]
hey thanks @benwaffle

yeh - just putting the dependencies into the meson.build file and doing a meson builddir sorted the intellisense out
thanks for that
